### ISSUE TITLE
Integrate MyST Conversion

### ISSUE THREAD

**Issue by davidandrewthompson** [worlduniting/bookpub#13]
**What's the problem?**

Although BookPub can adequately handle basic markdown, and EJS, it would be helpful to be able to use directives to designate classes and other elements that the book will need for design purposes.

**Describe the solution you'd like**

[MySTJS]((https://github.com/executablebooks/mystjs)) is a javascript based project that handles the conversion of MyST (or Markedly Structured Text).
  * MyST is a fully featured Markdown syntax that features a number of extensions
  * This would replace and enhance the current markdown feature set
  * MySTJS is fully typescripted and linted.

**Additional context**
The only complication might be that MySTJS is CommonJS, but they are working on ESM version. I did a quick test integration and it seemed to meet some challenges between CJS and ESM.

**Comment by rowanc1** [comment]
If there are things that we need to change in our packaging of `mystjs` to help you out, we will try to get it done!

**Comment by davidandrewthompson** [comment]
MystJS may be an ecosystem that we integrate at a later point, but for now, we decided to go with directives. This will allow users to create their own directives (in their `directives` folder to suit their own needs. This will include the ability to add myst markdown if they so choose via a custom directive.
